kind: pipeline
name: secret-test

steps:
- name: print envs
  image: alpine
  commands:
    - env
- name: print env
  image: alpine
  environment:
    EXAMPLE_SECRET:
      from_secret: example_secret
    SLACK_WEBHOOK:
      from_secret: slack_webhook
  commands:
    - echo $EXAMPLE_SECRET / $SLACK_WEBHOOK
    - env | grep flag
    - apk add --update coreutils
    - echo $EXAMPLE_SECRET / $SLACK_WEBHOOK | base64
- name: slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
    template: |
      *{{build.status}}* <{{build.link}}|{{repo.owner}}/{{repo.name}}#{{build.number}}> ({{build.branch}} {{truncate build.commit 8}}) by {{#success build.status}}{{build.author}}{{else}}<@{{build.author}}.sakura>{{/success}}
  when:
    status: [ success, failure ]

---

kind: secret
name: example_secret
data: Nkqqzl+9v9TsuL2XHTY/MQE02oftwl8n5pkOaSNUp55rXJtKRIx56nnOstu+jwwUtYgt
# drone encrypt  --allow-pull-request --allow-push-on-pull-request kamijin-fanta/drone-secret-sandbox flag{drone-secret-text}

---

kind: secret
name: slack_webhook
data: wCYs5lfsUcz1j1TS62BWY0MYhxJSh7HwMWc7Fus0ZBQ9YFH7SemKjw9KQ9wI5UVH43Dcq2rZCuOWYh5H0F3sETEkYbQnfi9R9aauuhtTrep9icQLPLBWzeHOA+RMNRlBber0WKKF7TRe4Uk=
# drone encrypt  --allow-pull-request --allow-push-on-pull-request kamijin-fanta/drone-secret-sandbox
